project:
  type: book

book:
  title: "My garden"
  author: "Rhian Davies"
  repo-url: https://www.github.com/statsrhian/garden
  repo-actions: [edit, issue]
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "About me"
      chapters: 
        - now.qmd
    - part: "Career ğŸ“"  
    - part: "Teaching ğŸ‘©â€ğŸ«" 
      chapters:
        - training.qmd
    - part: "Leadership â˜‚ï¸"
      chapters: 
        - leadership.qmd
        - teams.qmd
    - part: "Consultancy ğŸ’¼"
      chapters: 
        - consultancy.qmd
    - part: "How I work ğŸš€"
      chapters: 
        - tools.qmd
        - logging.qmd
        - remote-working.qmd
    - part: "Coding ğŸ‘©â€ğŸ’»"
      chapters:
        - code-style.qmd
        - coding-community.qmd
        - data-wrangling.qmd
        - git-tips.qmd
        - r.qmd
        - shiny.qmd
    - part: "Work-life balance ğŸ§˜â€â™€ï¸"
      chapters: 
        - remote-working.qmd
        - log-off.qmd
    - everything-else.qmd
    - part: "Book Notes ğŸ“–"
cover-image: flower.jpg
cover-image-alt: "A pretty flower I like"
navbar:
  search: true
bibliography: references.bib

format:
  html:
    number-sections: false
    code-overflow: wrap
    theme:
      - cosmo
      - brand



