project:
  type: book

book:
  title: "My garden"
  author: "Rhian Davies"
  page-footer:
    right: |
      Little thoughts from <a href="https://rhian.rbind.io/">Rhian Davies</a> ğŸŒ±. Built with <a href="https://quarto.org/">Quarto</a> ğŸ’œ.
  cover-image: flower.jpg
  cover-image-alt: "A pretty flower I like"
  navbar:
    search: true
  favicon: favicon.ico
  site-url: https://www.statsrhian-garden.netlify.app
  repo-url: https://www.github.com/statsrhian/garden
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Career ğŸ“"  
    - part: "Teaching ğŸ‘©â€ğŸ«" 
      chapters:
        - training.qmd
    - part: "Leadership â˜‚ï¸"
      chapters: 
        - communication.qmd
        - leadership.qmd
        - teams.qmd
    - part: "Consultancy ğŸ’¼"
      chapters: 
        - consultancy.qmd
    - part: "How I work ğŸš€"
      chapters: 
        - tools.qmd
        - logging.qmd
        - remote-working.qmd
    - part: "Coding ğŸ‘©â€ğŸ’»"
      chapters:
        - code-style.qmd
        - coding-community.qmd
        - data-wrangling.qmd
        - git-tips.qmd
        - r.qmd
        - shiny.qmd
    - part: "Work-life balance ğŸ§˜â€â™€ï¸"
      chapters: 
        - remote-working.qmd
        - log-off.qmd
    - everything-else.qmd
    - part: "Book Notes ğŸ“–"

format:
  html:
    number-sections: false
    code-overflow: wrap
    theme:
      - cosmo
      - brand
    author-meta: "Rhian Davies"



